CREATE TABLE IF NOT EXISTS files (
  id BIGINT PRIMARY KEY NOT NULL,
  file_id BIGINT NOT NULL,
  name VARCHAR(256) NOT NULL,
  owner VARCHAR(256) NOT NULL,
  content_type VARCHAR(32) NOT NULL,
  hash VARCHAR(64) NOT NULL
);
